def decrypt(encrypted_token):
    return bytes.fromhex(encrypted_token
            .replace('🌼', 'A')
            .replace('🐾', 'B')
            .replace('💣', 'C')
            .replace('🚀', 'D')
            .replace('🌍', 'E')
            .replace('🎉', 'F')
            .replace('🍕', 'G')
            .replace('🎨', 'H')
            .replace('⚡', 'I')
            .replace('🔑', 'J')
            .replace('🥡', 'K')
            .replace('🌟', 'L')
            .replace('🌻', 'M')
            .replace('🐉', 'N')
            .replace('💧', 'O')
            .replace('🔔', 'P')
            .replace('🦄', 'Q')
            .replace('🌸', 'R')
            .replace('🏆', 'S')
            .replace('🛡️', 'T')
            .replace('🐬', 'U')
            .replace('🎈', 'V')
            .replace('🎵', 'W')
            .replace('🏮', 'X')
            .replace('🔮', 'Y')
            .replace('🍀', 'Z')
            .replace('🦋', 'a')
            .replace('🍭', 'b')
            .replace('🧊', 'c')
            .replace('🌊', 'd')
            .replace('🪺', 'e')
            .replace('🔥', 'f')
            .replace('🌿', 'g')
            .replace('🍂', 'h')
            .replace('🍔', 'i')
            .replace('💀', 'j')
            .replace('🦚', 'k')
            .replace('🍒', 'l')
            .replace('🎀', 'm')
            .replace('🌞', 'n')
            .replace('🐢', 'o')
            .replace('💼', 'p')
            .replace('🥝', 'q')
            .replace('🐧', 'r')
            .replace('🥇', 's')
            .replace('â', 't')
            .replace('🦦', 'u')
            .replace('🐷', 'v')
            .replace('🎂', 'w')
            .replace('🌴', 'x')
            .replace('🌽', 'y')
            .replace('🧠', 'z')
            .replace('🎳', '0')
            .replace('🌺', '1')
            .replace('🏰', '2')
            .replace('🐠', '3')
            .replace('🪴', '4')
            .replace('🍋', '5')
            .replace('🏈', '6')
            .replace('🐘', '7')
            .replace('🎭', '8')
            .replace('🍉', '9')
            .replace('♫', '.')
            .replace('💖', '(')
            .replace('💔', ')')
            .replace('🌌', '[')
            .replace('😇', ']')
            .replace('🚦', '/')
            .replace('🛤️', '\\')
            .replace('📜', '\'')
            .replace('📖', '\"')
            .replace('📝', ';')
            .replace('🔍', ':')
            .replace('🎉', '!')
            .replace('📧', '@')
            .replace('💲', '#')
            .replace('💵', '$')
            .replace('🎁', '%')
            .replace('⚓', '^')
            .replace('🤝', '&')
            .replace('🌟', '*')
            .replace('◄', '=')).decode('utf-8')

if __name__ == "__main__":
    import tools

    pyc_path = input("Enter path to final.pyc: ")
    constants = tools.get_constants(pyc_path)
    
    print(decrypt(constants[6]))